# @format
name: Run scripts from dev branch

on:
    push:
        branches: [main]

jobs:
    generate_docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3.5.2
              with:
                  ref: dev
            - name: setup node
              uses: actions/setup-node@v1
              with:
                  node-version: 17
            - name: run script from dev branch
              run: node index-dev.js
            - name: push to dev branch
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git add .
                  git commit -m "Create docs/index.md from src/index.md 🤖"
                  git push
